post http://localhost:3000/auth/login
Content-Type: application/json

{"user":"Alice","password":"password"}

###
get http://localhost:3000/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkFsaWNlIiwiZW1haWwiOiJhbGljZUBwcmlzbWEuaW8iLCJpYXQiOjE2NzI1Mzc4NzMsImV4cCI6MTY3MjUzODQ3M30.A3EW1IV4GVkKtQzirom-bwOMRdQdj-XsdMTmcqtf-fI


###
get http://localhost:3000/user/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkFsaWNlIiwiZW1haWwiOiJhbGljZUBwcmlzbWEuaW8iLCJpYXQiOjE2NzI1Mzc4NzMsImV4cCI6MTY3MjUzODQ3M30.A3EW1IV4GVkKtQzirom-bwOMRdQdj-XsdMTmcqtf-fI